site_name: CloudCon 2025
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  palette:
    primary: white
    # accent: deep orange
  features:
    - navigation.tabs
# plugins:
#   - social
plugins: []
site_url: https://agardnerit.github.io/cloudcon
nav:
  - Home: "/"
  - Register: "./register"
  - Sponsors: "sponsors"
  - Agenda: "./agenda"
  - Speakers & Call for Papers: "./speakers"
  
extra:
  social:
      - icon: fontawesome/brands/linkedin 
        link: https://www.linkedin.com/company/cloudnativesydney
extra_css:
  - overrides/assets/stylesheets/extra.css
markdown_extensions: 
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg